# Generated by Terragrunt. Sig: nIlQXj57tbuaRZEa
provider "google" {
  project     = "cloud-cost-352410"
  region      = "us-central1"
}

terraform {
  required_providers {
    google = "5.22.0"
  }  
}
